x-deploy-settings: &deploy-settings
  mode: replicated
  replicas: 1
  resources:
    limits:
      cpus: "0.5"
      memory: 1G
services:
  challenge_01:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CHALLENGE_PATH: challenges/challenge-01
    ports:
      - "4000:1337"
    deploy: *deploy-settings
    restart: unless-stopped
    tty: true
    stdin_open: true
