x-deploy-settings: &deploy-settings
  mode: replicated
  replicas: 1
  resources:
    limits:
      cpus: "0.5"
      memory: 1G

x-build-settings: &build-settings
  context: .
  dockerfile: Dockerfile

x-common-settings: &common-settings
  deploy: *deploy-settings
  restart: unless-stopped
  tty: true
  stdin_open: true

services:
  challenge_01:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-01
    ports:
      - "4000:1337"

  challenge_02:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-02
    ports:
      - "4012:1337"

  challenge_03:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-03
    ports:
      - "4075:1337"
  
  challenge_04:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-04
    ports:
      - "4034:1337"

  challenge_05:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-05
    ports:
      - "4093:1337"
