x-deploy-settings: &deploy-settings
  mode: replicated
  replicas: 1
  resources:
    limits:
      cpus: "0.5"
      memory: 1G

x-build-settings: &build-settings
  context: .
  dockerfile: Dockerfile

x-common-settings: &common-settings
  deploy: *deploy-settings
  restart: unless-stopped
  tty: true
  stdin_open: true
   
services:
  challenge_01:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-01
        CHALLENGE_PORT: 4000
    ports:
      - "4000:4000"

  challenge_02:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-02
        CHALLENGE_PORT: 4012
    ports:
      - "4012:4012"

  challenge_03:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-03
        CHALLENGE_PORT: 4075
    ports:
      - "4075:4075"

  challenge_04:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-04
        CHALLENGE_PORT: 4034
    ports:
      - "4034:4034"

  challenge_05:
    <<: *common-settings
    build:
      <<: *build-settings
      args:
        CHALLENGE_PATH: challenges/challenge-05
        CHALLENGE_PORT: 4093
    ports:
      - "4093:4093"


